specVersion: 0.0.5
description: nft transfer example manifest
repository: 
schema:
  file: ./schema.graphql
dataSources:
  - kind: cosmos
    name: regchain
    network: localnet
    source:
      startBlock: 0
    mapping:
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Receive
        - List
      eventHandlers:
        - event: reward_list_proposal
          handler: handleListProposal
        
      transactionHandlers:
        - handler: handleTx
      file: ./src/mapping.ts
