// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: Executor.proto

package types

import (
	"context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TaskRequest struct {
	Taskhash             []byte   `protobuf:"bytes,1,opt,name=taskhash,proto3" json:"taskhash,omitempty"`
	RuleFile             string   `protobuf:"bytes,2,opt,name=rule_file,json=ruleFile,proto3" json:"rule_file,omitempty"`
	InputData            string   `protobuf:"bytes,3,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2b2cefa063d7008, []int{0}
}
func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (m *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(m, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetTaskhash() []byte {
	if m != nil {
		return m.Taskhash
	}
	return nil
}

func (m *TaskRequest) GetRuleFile() string {
	if m != nil {
		return m.RuleFile
	}
	return ""
}

func (m *TaskRequest) GetInputData() string {
	if m != nil {
		return m.InputData
	}
	return ""
}

type TaskResponse struct {
	Taskhash             []byte   `protobuf:"bytes,1,opt,name=taskhash,proto3" json:"taskhash,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorInfo            string   `protobuf:"bytes,3,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	OutputData           string   `protobuf:"bytes,4,opt,name=output_data,json=outputData,proto3" json:"output_data,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResponse) Reset()         { *m = TaskResponse{} }
func (m *TaskResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResponse) ProtoMessage()    {}
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2b2cefa063d7008, []int{1}
}
func (m *TaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResponse.Unmarshal(m, b)
}
func (m *TaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResponse.Marshal(b, m, deterministic)
}
func (m *TaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResponse.Merge(m, src)
}
func (m *TaskResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResponse.Size(m)
}
func (m *TaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResponse proto.InternalMessageInfo

func (m *TaskResponse) GetTaskhash() []byte {
	if m != nil {
		return m.Taskhash
	}
	return nil
}

func (m *TaskResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *TaskResponse) GetErrorInfo() string {
	if m != nil {
		return m.ErrorInfo
	}
	return ""
}

func (m *TaskResponse) GetOutputData() string {
	if m != nil {
		return m.OutputData
	}
	return ""
}

func (m *TaskResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskRequest)(nil), "request_proto.TaskRequest")
	proto.RegisterType((*TaskResponse)(nil), "request_proto.TaskResponse")
}

func init() { proto.RegisterFile("Executor.proto", fileDescriptor_e2b2cefa063d7008) }

var fileDescriptor_e2b2cefa063d7008 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x1d, 0x7f, 0x4a, 0x72, 0xdb, 0xba, 0x18, 0x51, 0x42, 0xaa, 0x58, 0xb2, 0xca, 0x2a,
	0x15, 0x7d, 0x03, 0xf1, 0x07, 0x37, 0x2e, 0x82, 0xab, 0x6e, 0xc2, 0x58, 0x6f, 0x6c, 0x68, 0xc8,
	0x8c, 0x73, 0xef, 0x80, 0x79, 0x1b, 0x1f, 0x55, 0x32, 0x69, 0xab, 0x82, 0x74, 0x79, 0xbf, 0xc3,
	0xf0, 0x9d, 0x39, 0x70, 0x7c, 0xff, 0x89, 0x0b, 0xc7, 0xda, 0x66, 0xc6, 0x6a, 0xd6, 0x72, 0x6c,
	0xf1, 0xc3, 0x21, 0x71, 0xe1, 0xcf, 0x04, 0x61, 0xf8, 0xa2, 0x68, 0x95, 0xf7, 0x50, 0xc6, 0x10,
	0xb0, 0xa2, 0xd5, 0x52, 0xd1, 0x32, 0x12, 0x53, 0x91, 0x8e, 0xf2, 0xed, 0x2d, 0x27, 0x10, 0x5a,
	0x57, 0x63, 0x51, 0x56, 0x35, 0x46, 0xfb, 0x53, 0x91, 0x86, 0x79, 0xd0, 0x81, 0x87, 0xaa, 0x46,
	0x79, 0x01, 0x50, 0x35, 0xc6, 0x71, 0xf1, 0xa6, 0x58, 0x45, 0x07, 0x3e, 0x0d, 0x3d, 0xb9, 0x53,
	0xac, 0x92, 0x2f, 0x01, 0xa3, 0xde, 0x43, 0x46, 0x37, 0x84, 0x3b, 0x45, 0x67, 0x30, 0x20, 0x56,
	0xec, 0xc8, 0x5b, 0x82, 0x7c, 0x7d, 0x75, 0x0e, 0xb4, 0x56, 0xdb, 0xa2, 0x6a, 0x4a, 0xbd, 0x71,
	0x78, 0xf2, 0xd4, 0x94, 0x5a, 0x5e, 0xc2, 0x50, 0x3b, 0xde, 0x76, 0x38, 0xf4, 0x39, 0xf4, 0xa8,
	0x2b, 0x21, 0xcf, 0x21, 0xa4, 0xea, 0xbd, 0x51, 0xec, 0x2c, 0x46, 0x47, 0x5e, 0xfa, 0x03, 0xae,
	0xe7, 0x10, 0x6c, 0xa6, 0x92, 0xcf, 0x30, 0x7e, 0x44, 0x5e, 0x17, 0x76, 0x35, 0xcb, 0x38, 0xfb,
	0x33, 0x5b, 0xf6, 0x6b, 0xb3, 0x78, 0xf2, 0x6f, 0xd6, 0xff, 0x33, 0xd9, 0x4b, 0xc5, 0x95, 0xb8,
	0x3d, 0x9d, 0x9f, 0x58, 0xac, 0x55, 0x8b, 0x76, 0x46, 0x06, 0x17, 0xed, 0x8c, 0x5b, 0x83, 0xf4,
	0x3a, 0xf0, 0x0f, 0x6e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x8a, 0x03, 0x40, 0xa4, 0x01,
	0x00, 0x00,
}


// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Executor_GetTaskResult_FullMethodName = "/request_proto.Executor/GetTaskResult"
)

// ExecutorClient is the client API for Executor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutorClient interface {
	GetTaskResult(ctx context.Context, opts ...grpc.CallOption) (Executor_GetTaskResultClient, error)
}

type executorClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutorClient(cc grpc.ClientConnInterface) ExecutorClient {
	return &executorClient{cc}
}

func (c *executorClient) GetTaskResult(ctx context.Context, opts ...grpc.CallOption) (Executor_GetTaskResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &Executor_ServiceDesc.Streams[0], Executor_GetTaskResult_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &executorGetTaskResultClient{stream}
	return x, nil
}

type Executor_GetTaskResultClient interface {
	Send(*TaskRequest) error
	Recv() (*TaskResponse, error)
	grpc.ClientStream
}

type executorGetTaskResultClient struct {
	grpc.ClientStream
}

func (x *executorGetTaskResultClient) Send(m *TaskRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *executorGetTaskResultClient) Recv() (*TaskResponse, error) {
	m := new(TaskResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExecutorServer is the server API for Executor service.
// All implementations must embed UnimplementedExecutorServer
// for forward compatibility
type ExecutorServer interface {
	GetTaskResult(Executor_GetTaskResultServer) error
	mustEmbedUnimplementedExecutorServer()
}

// UnimplementedExecutorServer must be embedded to have forward compatible implementations.
type UnimplementedExecutorServer struct {
}

func (UnimplementedExecutorServer) GetTaskResult(Executor_GetTaskResultServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTaskResult not implemented")
}
func (UnimplementedExecutorServer) mustEmbedUnimplementedExecutorServer() {}

// UnsafeExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutorServer will
// result in compilation errors.
type UnsafeExecutorServer interface {
	mustEmbedUnimplementedExecutorServer()
}

func RegisterExecutorServer(s grpc.ServiceRegistrar, srv ExecutorServer) {
	s.RegisterService(&Executor_ServiceDesc, srv)
}

func _Executor_GetTaskResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecutorServer).GetTaskResult(&executorGetTaskResultServer{stream})
}

type Executor_GetTaskResultServer interface {
	Send(*TaskResponse) error
	Recv() (*TaskRequest, error)
	grpc.ServerStream
}

type executorGetTaskResultServer struct {
	grpc.ServerStream
}

func (x *executorGetTaskResultServer) Send(m *TaskResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *executorGetTaskResultServer) Recv() (*TaskRequest, error) {
	m := new(TaskRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Executor_ServiceDesc is the grpc.ServiceDesc for Executor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Executor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "request_proto.Executor",
	HandlerType: (*ExecutorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTaskResult",
			Handler:       _Executor_GetTaskResult_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Executor.proto",
}
