// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/proto/specy/request/TaskRequest.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TaskRequest struct {
	Taskhash             []byte   `protobuf:"bytes,1,opt,name=taskhash,proto3" json:"taskhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf38f4ff4b6255e7, []int{0}
}
func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (m *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(m, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetTaskhash() []byte {
	if m != nil {
		return m.Taskhash
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskRequest)(nil), "specy.request.TaskRequest")
}

func init() {
	proto.RegisterFile("relayer/proto/specy/request/TaskRequest.proto", fileDescriptor_bf38f4ff4b6255e7)
}

var fileDescriptor_bf38f4ff4b6255e7 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2d, 0x4a, 0xcd, 0x49,
	0xac, 0x4c, 0x2d, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x2e, 0x48, 0x4d, 0xae, 0xd4,
	0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x0f, 0x49, 0x2c, 0xce, 0x0e, 0x82, 0xb0, 0xf5,
	0xc0, 0xf2, 0x42, 0xbc, 0x60, 0x05, 0x7a, 0x50, 0x05, 0x4a, 0x9a, 0x5c, 0xdc, 0x48, 0x6a, 0x84,
	0xa4, 0xb8, 0x38, 0x4a, 0x12, 0x8b, 0xb3, 0x33, 0x12, 0x8b, 0x33, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x78, 0x82, 0xe0, 0x7c, 0x27, 0xd1, 0x28, 0x61, 0x98, 0x55, 0x10, 0x4b, 0x4a, 0x2a, 0x0b, 0x52,
	0x8b, 0x93, 0xd8, 0xc0, 0xe6, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x38, 0xd4, 0x55,
	0x88, 0x00, 0x00, 0x00,
}
