specVersion: 0.0.5
description: regchain transfer example manifest
repository: https://github.com/RegTech-OXH/transfer-example-manifest
schema:
  file: ./schema.graphql
dataSources:
  - kind: cosmos
    name: regchain
    network: localnet
    source:
      startBlock: 0
    mapping:
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Transfer
      transactionHandlers:
        - handler: handleTx
      file: ./src/mapping.ts
