specVersion: 0.0.5
description: regchain system manifest
repository: https://github.com/RegTech-OXH/regchain-system-manifest
schema:
  file: ./schema.graphql
dataSources:
  - kind: cosmos
    name: regchain
    network: localnet
    source:
      startBlock: 0
    mapping:
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Rule
        - Relation
        - Binding
        - Block
      eventHandlers:
        - event: rule_proposal
          handler: handleRuleProposal
        - event: active_proposal
          handler: handleProposal
        - event: binding_proposal
          handler: handleBindingProposal
        - event: relation_proposal
          handler: handleRelationProposal
      blockHandlers:
        - handler: handleBlock
      file: ./src/mapping.ts
